spring:
  application:
    name: JournalApp
  data:
    mongodb:
      uri: mongodb+srv://arjunshekhawat2804:NTqILmvL8usTXUjr@cluster0.lbl62.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalApp
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /prod